### ISSUE TITLE
Database back end?

### ISSUE THREAD

**Issue by agartland** [nkullman/SIEVE#41]
It has occurred to me that we probably ought to be using a database to hold all the sieve analysis results. Each of the files we spec'd are probably a single table. Together the database could hold all the data for all analyses, including future trials, making it much more extensible.

This would also facilitate sharing of the data and I've realized while writing the paper, that data sharing is a critical motivation and service of this tool.

Do you guys have any database experience? I could create the database, but i'm not exactly sure how to pull the data into the browser/javascript. This should be pretty easy though.

This will also make future iterations with an analysis backend trivial as results would be passed from the computational backend to the frontend viz via the database.

Thoughts? Also feel free to checkout and edit the emerging draft on the google drive...

**Comment by gclenaghan** [comment]
I have experience with databases, however the entire app is written in javascript which shouldn't interface directly with a database since it's a client-side thing. We'd have to write server-side code (php, python, or similar) to interface with the database, and I'm not sure the best way to link that to our JS app.

**Comment by agartland** [comment]
Yes, I think I did this a bit a while ago with PHP: that's the way a blog or other content management system works I believe. Basically, the PHP pulls the data into the HTML DOM along with the JS when serving the HTTP request. Then the JS has access to the data in the DOM. Have you done this before? If no then I suppose I'd be inclined to find a python solution since I'm much more familiar with python at this point...

**Comment by nkullman** [comment]
I don't have any prior knowledge of databases or PHP to offer here
unfortunately, but I'm willing to learn and help implement it with a little
guidance from someone who's at least vaguely familiar with what they're
doing.

Nick

**Comment by agartland** [comment]
That's OK
